### ISSUE TITLE
Predenormalization converters

### ISSUE THREAD

**Issue by etki** [ama-team/ruby-entity-mapper#19]
There are quite common cases of pre-denormalization conversion:

- If input is String or Symbol, wrap it as `{ User: input }`
- If input is nil, use empty hash instead
- If there's no :id field, take the Nth segment from the path
- Take everything in the input hash but fields `user`, `options`, and put it into `options` key:

```yml
user: git
identity_file: ~/.ssh/id_rsa
options:
  host: tiesto.com
```
->
```yml
user: git
options:
  identity_file: ~/.ssh/id_rsa
  host: tiesto.com
```

It's exaggerating to write them every time, so, probably, they should come as a bundled library
